### ISSUE TITLE
[question]Can I use multiples authors?

### ISSUE THREAD

**Issue by BeatrizCarvalho** [maxpou/gatsby-starter-morning-dew#79]
Hello,
Sorry for the question because I'm a gatsby new user.
So,  can I use multiples authors per blog page? How can I do this? Where need I configure?

Thank you for your attention and thank you for good work in your template.

**Comment by maxpou** [comment]
Hey @BeatrizCarvalho,

Welcome there and thank you for this kind words!
If you use this repo as...

- a **theme** (via npm), it's not possible to do multi-author.
- a **starter** (git clone / gatsby cli) you gonna have to tweak a little bit this starter because it's not possible. But, you can check what @JeroenKnoops did with https://040code.github.io/ (GitHub repo: https://github.com/040code/040code.github.io). It's a blog based on this starter which support multiple authors!

Cheers :)
